# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8r6u9j6sc1c73asd94g-a:5432/noctification
spring.datasource.username=noctification_user
spring.datasource.password=cyDlNonXUbtPrklD89gLHmEYmwgMfnDi
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Mail Properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yuvarajramadassram@gmail.com
spring.mail.password=dotm sqrr soln foov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=AC4345c304f3684246e9e6651344bb7691
twilio.auth.token=f1d1a422cfac9f1112b80f2b4fd02d5e
twilio.phone.number=+15075700632